[build]
  base = "client"
  command = "npm ci && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "22", NPM_FLAGS = "--include=dev" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200